/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings cloudflare-bindings.generated.d.ts` (hash: e5e37db788d729fcd97d1757608e34af)
interface __BaseEnv_CloudflareBindings {
	IMAGE_BUCKET: R2Bucket;
	DB: D1Database;
	AI: Ai;
	ASSETS: Fetcher;
	DEMO_MODE: string;
	MAX_UPLOAD_MIB: string;
	ADMIN_PASSWORD: string;
	SESSION_SECRET: string;
	IP_HASH_SECRET: string;
	CONFIG_ENCRYPTION_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./custom-worker");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEMO_MODE" | "MAX_UPLOAD_MIB" | "ADMIN_PASSWORD" | "SESSION_SECRET" | "IP_HASH_SECRET" | "CONFIG_ENCRYPTION_KEY">> {}
}
