name = "image"
main = "src/index.ts"
compatibility_date = "2024-07-01"

[assets]
directory = "./public"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"

[placement]
mode = "smart"
